adding my artsyness to the project
zero-to-mastery/Animation-Nation pull request #1508
Opened 2022-04-26 16:01 UTC by nisan137

Please add me to this list. @royranger

2022-04-28 14:14 UTC, donmarvex commented on include.js
> +  {
Please add the artName property and value

2022-04-28 14:16 UTC, donmarvex commented on include.js
> +];
Also remove extra closing square bracket

2022-04-28 14:17 UTC, donmarvex requested changes
Hey Anis, please check these changes and resolve the merge conflicts.

2022-05-10 12:06 UTC, donmarvex commented
Hello @nisan137 , you have not made the requested changes to your PR.

2022-05-10 13:25 UTC, nisan137 commented
hii i did the changes


‫בתאריך יום ג׳, 10 במאי 2022 ב-15:06 מאת ‪Marvelous Emoghene‬‏ <‪
***@***.***‬‏>:‬

> Hello @nisan137 <https://github.com/nisan137> , you have not made the
> requested changes to your PR.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zero-to-mastery/Animation-Nation/pull/1508#issuecomment-1122302544>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXRRENXBCVCC7BDWEGS6QB3VJJGMLANCNFSM5UMKW4RQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-10 14:57 UTC, nisan137 commented
Ok I will do it soon :)

בתאריך יום ג׳, 10 במאי 2022, 16:37, מאת Marvelous Emoghene ‏<
***@***.***>:

> @nisan137 <https://github.com/nisan137> , please you also need to add the
> "artName" property and value.
> Also
>
> @nisan137 <https://github.com/nisan137> A possible conflict has been
> detected, you will need to resolve this before your pull request can be
> merged. The most common reason conflicts occur, is when the contributor
> does not run git pull origin master before pushing their new changes.
>
> You also have to run the command before pushing your changes.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zero-to-mastery/Animation-Nation/pull/1508#issuecomment-1122407983>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXRRENWCGOTLOJILFOPOXCLVJJRDFANCNFSM5UMKW4RQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-06-04 03:33 UTC, closed without merging