added my animation box-rotate-animation
zero-to-mastery/Animation-Nation pull request #1529
Opened 2022-05-20 06:48 UTC by Life1sOk

Hi, thanke you. Have a nice day

2022-05-20 07:27 UTC, donmarvex requested changes

2022-05-20 07:27 UTC, donmarvex commented on include.js
> +    pageLink: './Art/box-rotate-animation/index.html',
Please add the "artName" property and give your art a nice name!

2022-05-20 20:37 UTC, donmarvex commented
Hi @Life1sOk , thank You for making the changes but the contribution guidelines require you to perform this step outlined below;

**_5. Get a screen recording of your finished work, and make a gif! Try to crop it so that it looks good as a smallish (preferably squarish) image. Save this in your directory, together with your HTML and CSS files. Static screenshots are also acceptable.
If you don't add a gif/screenshot, the website won't show your animation._**

So I'd really like you to make this change in order for your animation to be displayed on the web application.

2022-05-21 06:38 UTC, donmarvex approved these changes
Everything looks great! Thank You.

2022-05-21 06:39 UTC, donmarvex commented
All good here @sophiabrandt

2022-05-21 06:46 UTC, Life1sOk commented
Thank you for your help

2022-05-22 07:57 UTC, merged