Include.js changes
zero-to-mastery/Animation-Nation pull request #1956
Opened 2023-10-07 06:45 UTC by Hrishap

Recommended changes  made in include.js

2023-10-07 07:45 UTC, sophiabrandt requested changes

2023-10-07 07:45 UTC, sophiabrandt commented on include.js
> +
please don't reformat existing code. An empty line is not necessary here.

2023-10-07 07:45 UTC, sophiabrandt commented on include.js
> +
This is missing the closing bracket and comma `},`. Also, please no empty lines between entries.

2023-10-07 07:45 UTC, sophiabrandt commented on include.js
> +
same here.

2023-10-07 07:45 UTC, sophiabrandt commented on include.js
> +
same here.

2023-10-09 11:18 UTC, Hrishap commented
respected changes done :)

2023-10-09 16:44 UTC, MattCSmith approved these changes
Looks good to me. Nice job 👍

2023-10-09 16:45 UTC, merged