Add Face animation
zero-to-mastery/Animation-Nation pull request #1961
Opened 2023-10-07 09:58 UTC by pabitra0011

Add face animation using Html and Css only.

![face animation gif](https://github.com/zero-to-mastery/Animation-Nation/assets/94389910/9d454299-c8dd-43e9-83f2-5d81e4daca18)

2023-10-07 11:00 UTC, sophiabrandt requested changes

2023-10-07 11:00 UTC, sophiabrandt commented on include.js
> +    `</li>`
I would appreciate it if you don't change the formatting here. Same as in my comments in #1952

2023-10-07 11:01 UTC, sophiabrandt commented
@pabitra0011 Please add the requested changes here instead of closing this pull request and opening a new one. This adds an additional burden on the maintainers.

2023-10-09 18:17 UTC, MattCSmith approved these changes
Looks good to me. Nice job 👍

2023-10-09 18:17 UTC, merged