Ball Hitting
zero-to-mastery/Animation-Nation pull request #2021
Opened 2023-10-10 13:30 UTC by Kamalesh-Seervi

I have added a simple animated ball hitting. Please merge my pull request

2023-10-10 19:21 UTC, sophiabrandt requested changes
Please check the contribution guide in the README.md file. You need to edit the `include.js` file in the root folder.

2023-10-13 12:18 UTC, MattCSmith commented
Hey @Kamalesh-Seervi 
Just checking in on this PR and noticed the includes.js still needs to be added to the submission.
If you need help please feel free to reach out in the #hacktoberfest channel over on Discord

2023-10-14 15:00 UTC, Kamalesh-Seervi commented
changes done in include.js

2023-10-14 22:59 UTC, MattCSmith approved these changes

2023-10-14 22:59 UTC, merged