Added Square Bouncing Animation
zero-to-mastery/Animation-Nation pull request #2120
Opened 2023-10-13 18:53 UTC by tvermaashutosh

![temp2](https://github.com/zero-to-mastery/Animation-Nation/assets/96707067/4c4a9124-b48e-4eb8-bf3c-7574d375d0d1)

2023-10-13 19:58 UTC, sophiabrandt requested changes
Thanks for this new contribution.

Please check the following checklist that you need to fulfill for us to be able to merge your request.

Please see the [Guide in README.md](https://github.com/zero-to-mastery/Animation-Nation#how-to-contribute) for further details.

##  Checklist
- [x] created a submission into the `./Art` folder
- [ ] the contribution folder in `./Art` is the contributor's Github name
- [ ] has a gif or png file of the animation
- [ ] can find the html 
- [ ] can find the style (css file)
- [ ] modified `include.js` **with the right details**

## Issues: 

- Please see the other suggestions in this PR.

Please refer to the `README.md` file for guidance and follow the guidelines.
If you have questions feel free to reach to the discord or ask them here.

2023-10-13 19:58 UTC, sophiabrandt commented on Art/Ash/style.css
> +    } */
Please remove code that has no use (outcommented code).

2023-10-13 19:58 UTC, sophiabrandt commented on include.js
> +  },
Please remove the comments, there were only added in the README to explain what to do.

Also, please fill out the details with the name/folder path of _your contribution_.

Your folder name should be the Github username.  The file name should be the name of _your contribution_.

So, i.e. `pageLink: './Art/tvermaashutosh/index.html`.

2023-10-13 19:58 UTC, sophiabrandt commented on Art/Ash/index.html
> +    <title>Document</title>
Nitpick/Suggestion:

Change the `title` to something that's more suitable.


This is just a suggestion and not following it won't stop us from merging your contribution.

2023-10-13 19:58 UTC, sophiabrandt commented on Art/Ash/index.html
> +    <link rel="stylesheet" href="styling.css">
The css file name you commited is `style.css`, so the `href` should point to that file.

2023-10-14 09:25 UTC, tvermaashutosh commented
@sophiabrandt 
Please review and merge my PR. I have made all the suggested changes.

2023-10-14 13:43 UTC, sophiabrandt commented
@tvermaashutosh Thank you for your contribution.

Unfortunately, there are still some items open:

Please see the [Guide in README.md](https://github.com/zero-to-mastery/Animation-Nation#how-to-contribute) for further details.

##  Checklist
- [x] created a submission into the `./Art` folder
- [ ] the contribution folder in `./Art` is the contributor's Github name
- [x] has a gif or png file of the animation
- [x] can find the html 
- [x] can find the style (css file)
- [ ] modified `include.js` **with the right details**


If you have questions feel free to reach to the discord or ask them here.

2023-10-14 13:44 UTC, sophiabrandt requested changes

2023-10-14 13:44 UTC, sophiabrandt commented on include.js
> +  },
The entry still does not meet the necessary requirements.

a) the folder names for your contribution should match your github name
b) the links should conform to the file names, i.e. `pageLink: './Art/tvermaashutosh/index.html`

2023-10-14 14:01 UTC, tvermaashutosh commented
@sophiabrandt 
Please review and merge my PR. I have made all the suggested changes again. 🙂🙂

2023-10-14 14:02 UTC, merged