3d toaster animation
zero-to-mastery/Animation-Nation pull request #2130
Opened 2023-10-14 05:38 UTC by apu52

I have added a new project on 3D toaster animation & have added a gif file with it.
I have made it using HTML & CSS
Please take a look at my PR & please merge it.

2023-10-14 05:38 UTC, apu52 commented
@l-white Please take a review of my PR & merge it.

2023-10-14 14:17 UTC, LaurelineP commented
Gif has a fail to start audio that could be avoided :)

2023-10-21 04:40 UTC, apu52 commented
@l-white Please take a review of my PR & merge it. I have added the correct GIF file & have updated the include.js file

2023-10-23 11:08 UTC, apu52 commented
@l-white Please take a review of my PR & merge it. I have added the correct GIF file & have updated the include.js file

2023-10-23 11:08 UTC, apu52 commented
@l-white Please take a review of my PR & merge it. I have added the correct GIF file & have updated the include.js file

2023-10-23 13:15 UTC, apu52 commented
@l-white Please take a review of my PR & merge it. I have added the correct GIF file & have updated the include.js file

2023-10-27 20:28 UTC, LaurelineP requested changes
Both your html and css file seems to override a prior contributions
-  Please let us know what you want to do 
- Please adjust your files and folder
For any guidance please refer to the README.md file

2023-10-27 20:28 UTC, LaurelineP commented on include.js
> +    githubLink: 'https://github.com/https://github.com/apu52'
# Feedbacks on include js content
- [ ] invalid githubLink url > `https://github.com/https://github.com/apu52`
- [ ] invalid imageLink > this does not convey with a folder name you added a link which in incorrect
- [ ] invalid pageLink > this does not convey with a folder name you added a link which in incorrect
Please check the example on the readme.md file and correctly modify your PR 
--- 
also note that your file must not have any space character in their names
--> this should includes modifications based on your folder structure and file renaming

2023-10-27 20:28 UTC, LaurelineP commented on Art/apu52/3D Toaster.gif
# Feedback - gif file name
Please rename the file so there are no space - use letters, digits, hyphens or underscore instead

2023-10-31 16:19 UTC, closed without merging