glowing flower animation
zero-to-mastery/Animation-Nation pull request #2133
Opened 2023-10-14 09:27 UTC by saurabhsingh720

![fl](https://github.com/zero-to-mastery/Animation-Nation/assets/106748434/64ddd458-91d8-401e-b69c-48917cda573b)
Glowing flower animation

2023-10-14 14:00 UTC, sophiabrandt commented
@saurabhsingh720  Thanks for this contribution. 🎉 

Please check the following checklist that you need to fulfill for us to be able to merge your request.

Please see the [Guide in README.md](https://github.com/zero-to-mastery/Animation-Nation#how-to-contribute) for further details.

##  Checklist
- [x] created a submission into the `./Art` folder
- [ ] the contribution folder in `./Art` is the contributor's Github name
- [x] has a gif or png file of the animation
- [x] can find the html 
- [x] can find the style (css file)
- [ ] modified `include.js` **with the right details**

## Issues: 

- missing changes to `include.js`
- wrong folder name

Please refer to the `README.md` file for guidance and follow the guidelines.
If you have questions feel free to reach to the discord or ask them here.

2023-10-14 17:23 UTC, saurabhsingh720 commented
issue resolved please check it

2023-10-14 19:04 UTC, sophiabrandt commented on include.js
> +    pageLink: './Art/flower-animation/index.html',
This needs to correspond with the folder name, e.g. `Art/saurabhsingh720/index.html`

2023-10-14 19:04 UTC, sophiabrandt requested changes

2023-10-14 19:04 UTC, sophiabrandt commented on include.js
> +    imageLink: './Art/fl.gif',
Same here.

2023-10-15 04:40 UTC, saurabhsingh720 commented
@sophiabrandt  your requested change has been made. Please review it.

2023-10-15 10:49 UTC, merged