Banana Float with Animated Eyes
zero-to-mastery/Animation-Nation pull request #2134
Opened 2023-10-14 09:55 UTC by golneshin

This a ZTM project which is a challenge in Hacktoberfest. The challenge asked for at least one animation, then I created this project that included three animations.

2023-10-14 14:28 UTC, LaurelineP commented
Hi there, congrats and thanks for the contribution 🚀 
Your contribution is missing the `include.js` modification, could you do it please? 
If any questions, this is explained on the README.md file :)

2023-10-27 20:32 UTC, LaurelineP requested changes
Please also provide the modifications for the `incude.js` file

2023-10-27 20:32 UTC, LaurelineP commented on Art/golneshin_mardomak/mardomak.html
> +  <script src='main.js'></script>
# Feedback - no script tag in html file
Please remove the line with the script tag

2023-11-11 22:20 UTC, l-white commented
Closing pull request due to inactivity.

2023-11-11 22:20 UTC, closed without merging