Seurat's style art
zero-to-mastery/Animation-Nation pull request #2170
Opened 2023-10-16 10:10 UTC by HarrisMBrad

We embark on an artistic adventure. Seurat's style, mirroring, we shall, with pointillistic precision. In the intricate world of meticulously placed dots and vibrant colors, we shall immerse ourselves, ready to forge a truly unique and captivating piece. 
A harmonious collaboration between human creativity and AI's artistic prowess shall bring forth this creation.

2023-11-01 08:13 UTC, sophiabrandt requested changes

2023-11-01 08:13 UTC, sophiabrandt commented on README.md
> +[![An image of @7597243's Holopin badges, which is a link to view their full Holopin profile](https://holopin.me/7597243)](https://holopin.io/@7597243)
Please remove this addition.

2023-11-01 08:13 UTC, sophiabrandt commented on Art/Groot-2001/style.css
>  }
Please rollback changes to this file.

2023-11-12 10:40 UTC, sophiabrandt commented
Closing this due to inactivity.

2023-11-12 10:42 UTC, sophiabrandt commented
@HarrisMBrad are you still interested in getting this merged? It looks like my comments above were not yet addressed.

If you solved those points, please mark the discussions as resolved.

2023-11-12 15:50 UTC, HarrisMBrad commented
Sure, if it's not merging, it's probably my fault. Formatting for this was my issue.  Is it mergable?

2023-11-12 17:04 UTC, sophiabrandt commented
Not currently, no. You would need to fix the issues discussed above in the comments.

2023-11-15 04:09 UTC, l-white commented
@HarrisMBrad The last several commits have been empty, and given the complicated history of commits, I would advise starting a new branch and submitting your changes. If you have any questions, please feel free to ask for help on the ZTM Discord server. It can take time and practice to learn version control, and I encourage you to keep trying.

2023-11-15 04:09 UTC, closed without merging

2023-11-15 11:20 UTC, HarrisMBrad commented
Ok... I might do that. Thanks for any advice. It was the .yml or formatting that I can't seem to get right.