amandeepsinghparihar
zero-to-mastery/Animation-Nation pull request #2189
Opened 2023-10-17 12:18 UTC by amandeep-singh-parihar

2023-10-17 16:13 UTC, LaurelineP requested changes

2023-10-17 16:13 UTC, LaurelineP commented on include.js
> +
# Feedbacks
Please remove the comments :)

2023-10-17 16:42 UTC, amandeep-singh-parihar commented
done all the necessary changes.

2023-10-28 08:37 UTC, LaurelineP commented
Hi there, thanks for replying.
Exceptionally I've fixed some points on your MR
- folder's name that should be your user github name -> was missing hyphens
- removed space in your pictural file name
- and fixed your include.js --> you left the "chevron" - which are marks to state those are placeholder.
- also correct the path resolution
in order to move forwards.
It is exceptional as those were not mentioned on the feedbacks earlier and because you did get back to the MR :)

Happy hacktoberfest @amandeep-singh-parihar 🙌

2023-10-28 08:37 UTC, merged