Anima nation
zero-to-mastery/Animation-Nation pull request #2193
Opened 2023-10-17 15:08 UTC by bingo9813

I redid this project from scratch. Originally I was missing some data I was required to add to the include.js (I did as it was described in the instruction). Hopefully this time it's good.
Please, add me to the list.

2023-10-17 22:51 UTC, LaurelineP requested changes

2023-10-17 22:51 UTC, LaurelineP commented on Animation-Nation
# Feedbacks
Here you have a folder you want to remove 
Please remove this folder in order to be able to merge your contribution :)

2023-10-28 08:48 UTC, LaurelineP commented
Before we could merge your contribution, the following feedbacks need to be addressed first.
Please address the given feedbacks

# Feedbacks
- [ ] your forlder name does not match your github username, please rename it accordingly
- [ ] include.js modifications should be reviewed once you changed the forlder name accordingly

## Acceptance criteria for a contribution
- [ ] the contribution includes a new folder named after the author github user name  in `./Art`
- [x] the contribution includes an HTML file
    - [x] no CSS
    - [x] no JS
    - [x] no embedded  SVG 
    - [x] has a `<link>` tag to the CSS file
- [x] the contribution includes a CSS file
- [x] the contribution includes the animated file (gif) or picture (jpeg, jpg, png )
    _the pictural representation must not include the browser frame, just the animation_
- [ ] the contribution includes the correct contribution's details in `include.js`

Please address the above feedbacks and/or unchecked acceptance criteria - if you need guidance , please refer to the `README.md` file.

2023-11-15 04:06 UTC, l-white commented
Closing PR due to inactivity

2023-11-15 04:06 UTC, closed without merging