added a monkey animation
zero-to-mastery/Animation-Nation pull request #2247
Opened 2023-10-20 10:49 UTC by daniel1david

Hi, please add my contribution. 
Thank you!

2023-10-21 15:55 UTC, LaurelineP requested changes
Thanks for your contribution 🙌
Please address the feedbacks above in order to proceed your PR

2023-10-21 15:55 UTC, LaurelineP commented on Art/daniel1david/art_style.css
> +/*	background: white;*/
# Context
```js
/*	background: white;*/
```

# Feedback - unnecessary comment
Please remove the un used comment

2023-10-21 15:55 UTC, LaurelineP commented on Art/daniel1david/art_style.css
> +}
# Context
```js
.left-eye::after {
  content: "";
  position: absolute;
  top: -3%;
  left: -5%;
  height: 0;
  width: 110%;
  border-radius: 50%;
  background: saddlebrown;
  -webkit-animation: blink 3s infinite ease-in;
  animation: blink 3s infinite ease-in;
   z-index: 4;
}
```

# Feedback - stay consistent
Please try to remain consistent across your own code ( previous block of code has a different indentation ) - 
this should be indented in the same way

2023-10-21 15:55 UTC, LaurelineP commented on Art/daniel1david/art_style.css
> +}
# Context
```js
.right-eye::after {
  content: "";
  position: absolute;
  top: -3%;
  left: -5%;
  height: 0;
  width: 110%;
  border-radius: 50%;
  background: saddlebrown;
  -webkit-animation: blink 3s infinite ease-in;
  animation: blink 3s infinite ease-in;
  z-index: 4;
}
```

# Feedback - stay consistent ( indentation ) 
Please try to remain consistent across your own code ( previous block of code has a different indentation ) - 
this should be indented in the same way

2023-10-21 15:55 UTC, LaurelineP commented on Art/daniel1david/art_style.css
> +
# Context
```js
/*help from 'https://blog.hubspot.com/website/css-animation-examples#:~:text=To%20make%20a%20CSS%20animation,animation%2C%20like%20speed%20and%20delay.'*/
```

# Feedback - unnecessary comment
Please remove the un used comment

2023-10-25 07:10 UTC, daniel1david commented
I made the changes to those files. 
Shocked that I didn't have the same styling throughout the whole file; thanks for spotting that!
@LaurelineP

2023-10-25 23:33 UTC, merged