adding my art to list
zero-to-mastery/Animation-Nation pull request #2353
Opened 2023-10-26 12:41 UTC by Pariskarpoudel

plz addme

2023-10-26 12:43 UTC, Pariskarpoudel commented
adddddddd

2023-10-27 14:05 UTC, sophiabrandt requested changes
Please move your artwork into a folder that has the same name as your Github username.

For details, see the instructions in the README file.

2023-10-27 14:05 UTC, sophiabrandt commented on include.js
> +    githubLink: 'https://github.com/Pariskarpoudel' // change this
Please remove the comments and adjust your entry with the correct details (see other comment).

2023-10-29 14:15 UTC, LaurelineP commented
Before we could merge your contribution, the following feedbacks need to be addressed first.
Please address the given feedbacks

# Feedbacks
- [ ] your contribution folder is not named as your github username
- [ ] gif file is empty - please provide a valid gif file

## Acceptance criteria for a contribution
- [ ] the contribution includes a new folder named after the author github user name  in `./Art`
- [x] the contribution includes an HTML file
    - [x] no CSS
    - [x] no JS
    - [x] no embedded  SVG 
    - [x] has a `<link>` tag to the CSS file
- [x] the contribution includes a CSS file
- [ ] the contribution includes the animated file (gif) or picture (jpeg, jpg, png )
    _the pictural representation must not include the browser frame, just the animation_
    Your gif file has no content ( you can check that on the PR' changes tab )
- [x] the contribution includes the correct contribution's details in `include.js`

Please address the above feedbacks and/or unchecked acceptance criteria - if you need guidance , please refer to the `README.md` file.

2024-09-19 23:51 UTC, closed without merging