Animated cards
zero-to-mastery/Animation-Nation pull request #2715
Opened 2024-10-11 04:56 UTC by PragyaTripathi990

Thank you for making a pull request to ZTM's Animation Nation project. We will review your pull request as soon as we can, but keep in mind we can get very busy during Hacktoberfest.

While you're waiting, please look over this checklist. Feel free to write a description of what you did as well!

## What I did

I have have created cards that shows animation on hover. I hope you would merge my PR.

## Pull request checklist

- [x] This pull request uses **HTML and CSS** only and provides a `meta.json` file.
- [x] All files in this pull request are in a directory named: `<github_username>-<art_name>` without the <>.
- [x] Your pull request contains `index.html` and `styles.css`.
	- [x] Your html file is named exactly: `index.html`
	- [x] Your css file is named exactly: `styles.css`
- [x] Your pull request your `meta.json` with:
	- [x] `githubHandle`: being your unique github user name,
	- [x] `artName` : name of your animation
- [x] Your submission includes **at least one animation**.
- [x] Your pull request **does not modify any other files** in the repository.

#### Not normally needed
- [ ] Check this if you would like to discuss an improvement besides adding animations

**Note: if your pull request makes an improvement besides adding a CSS animation you will need to discuss this with the maintainers. You can help kickstart this process by explaining what your change does and why you are making it in the "What I did" section**

## What to expect

- If your pull request meets the checklist requirements it will be approved and merged by a maintainer
- If your pull request needs some changes. A maintainer will leave a comment requesting changes
- If your pull request significantly violates the criteria in the checklist it will be closed with feedback.

2024-10-11 10:22 UTC, LaurelineP requested changes
Aloha and thanks for your contribution 🙌
Before we could merge your PR please address the given feedbacks :
- Please remove the commented css rules
- your contribution is missing a `meta.json` file ( see the README.md file )  :)

2024-10-11 10:22 UTC, LaurelineP commented on Art/PragyaTripathi990-cardsAnimation/styles.css
## CSS comments 
Please removed the commented CSS rules

2024-10-12 10:43 UTC, LaurelineP requested changes
Also, you need to add a `meta.json`  you could read about here 
[README.md]([Code](https://github.com/zero-to-mastery/Animation-Nation))
as you can see in you PR template 
- [ ] Missing `meta.json` : please add your `meta.json` file in the folder :)

2024-10-12 10:43 UTC, LaurelineP commented on Art/PragyaTripathi990-cardsAnimation/styles.css
> +}  */
- [ ] There are still commented blocks you could remove here

2024-10-12 10:43 UTC, LaurelineP commented on Art/PragyaTripathi990-cardsAnimation/styles.css
> +    /* background: linear-gradient(135deg, #8A2BE2, #DA70D6); */
- [ ] There are still commented lines you could remove here :)

2024-10-13 16:48 UTC, PragyaTripathi990 commented
@LaurelineP Hey, I am done with the requested changes! Can you please review it.

2024-10-14 08:42 UTC, merged