Solar system animation
zero-to-mastery/Animation-Nation pull request #2775
Opened 2024-10-18 13:36 UTC by HossamGouda

Solar system animation using css and Html only .

2024-10-18 15:45 UTC, LaurelineP requested changes
Aloha @HossamGouda and thanks for your contribution.
In order to merge your merge requests, please address the following:
- [ ] Please address the given feedbacks
- [ ] Please address the following other feedbacks
     - [ ] Your folder for the rocket launch contain a speace in the name, please remove the space

2024-10-18 15:45 UTC, LaurelineP commented on Art/HossamGouda-Rocket -Launch/index.html
## HTML to review for css file name change
- [ ] Once you've renamed the css file according to the Readme description, please adjust the name in link tag

2024-10-18 15:45 UTC, LaurelineP commented on Art/HossamGouda-Rocket -Launch/style.css
## CSS filename
- [ ] Please rename your file as mentioned in the readme.md file

2024-10-19 09:17 UTC, HossamGouda commented
This branch only for the Solar system animation. kindly let me know for any further requested updates !

2024-10-19 09:22 UTC, LaurelineP commented
All good to go :) thanks for your reactivity 🙌

2024-10-19 09:23 UTC, merged