A beautiful animation added
zero-to-mastery/Animation-Nation pull request #2789
Opened 2024-10-19 17:16 UTC by Kaif-Azmi

Thank you for making a pull request to ZTM's Animation Nation project. We will review your pull request as soon as we can, but keep in mind we can get very busy during Hacktoberfest.

While you're waiting, please look over this checklist. Feel free to write a description of what you did as well!

## What I did

*Made an animation of circles using html and css only.

## Pull request checklist

- [ ] This pull request uses **HTML and CSS** only and provides a `meta.json` file.
- [ ] All files in this pull request are in a directory named: `Kaif-Azmi-Colour-Fill` without the <>.
- [ ] Your pull request contains `index.html` and `styles.css`.
	- [ ] Your html file is named exactly: `index.html`
	- [ ] Your css file is named exactly: `styles.css`
- [ ] Your pull request your `meta.json` with:
	- [ ] `githubHandle`: being your unique github user name,
	- [ ] `artName` : name of your animation
- [ ] Your submission includes **at least one animation**.
- [ ] Your pull request **does not modify any other files** in the repository.

#### Not normally needed
- [ ] Check this if you would like to discuss an improvement besides adding animations

**Note: if your pull request makes an improvement besides adding a CSS animation you will need to discuss this with the maintainers. You can help kickstart this process by explaining what your change does and why you are making it in the "What I did" section**

## What to expect

- If your pull request meets the checklist requirements it will be approved and merged by a maintainer
- If your pull request needs some changes. A maintainer will leave a comment requesting changes
- If your pull request significantly violates the criteria in the checklist it will be closed with feedback.

2024-10-19 21:28 UTC, LaurelineP requested changes
Aloha @Kaif-Azmi 
- Please address the feedbacks

2024-10-19 21:28 UTC, LaurelineP commented on index.html
# HTML outside of a folder contribution + git diff conflict committed
- [ ] Please put this file into a folder name as followed <github-username>-<art-name>
- [ ] Please remove any conflict text committed
```
<<<<<<< HEAD
=======
>>>>>>> 74a8e399268818720203f64721394c909b95ba9f

2024-10-19 21:28 UTC, LaurelineP commented on meta.json
# Meta seems to reflects another folder in same PR
It seems like the meta reflect the folder Kaif-Azmi-SubmitBtn, in which case this may be a mistake
- either you want to submit a new contribution 
- etiher it is a duplicated file that you would not want to track
- [ ] Please resolve if this is a new contribution 
 - you need to create the folder and move the ./index.html ./styles.css and ./meta.json inside
 - you probably would like to name it differently maybe

2024-10-19 21:28 UTC, LaurelineP commented on styles.css
# Similar / Duplicated styles.css 
As mentioned ealier - it seems like you have the same files in kaif-azmi-submitBtn-Animation
- Please remove the files
- or Please put them in a folder

2024-10-20 10:01 UTC, Kaif-Azmi commented
Fixed all the issues.

2024-10-20 14:30 UTC, merged