violin87-activeSquares
zero-to-mastery/Animation-Nation pull request #2791
Opened 2024-10-19 22:28 UTC by violin87

Thank you for making a pull request to ZTM's Animation Nation project. We will review your pull request as soon as we can, but keep in mind we can get very busy during Hacktoberfest.

While you're waiting, please look over this checklist. Feel free to write a description of what you did as well!

## What I did

*Optional: Edit this to tell us what you did!*

## Pull request checklist

- [ ] This pull request uses **HTML and CSS** only and provides a `meta.json` file.
- [ ] All files in this pull request are in a directory named: `<github_username>-<art_name>` without the <>.
- [ ] Your pull request contains `index.html` and `styles.css`.
	- [ ] Your html file is named exactly: `index.html`
	- [ ] Your css file is named exactly: `styles.css`
- [ ] Your pull request your `meta.json` with:
	- [ ] `githubHandle`: being your unique github user name,
	- [ ] `artName` : name of your animation
- [ ] Your submission includes **at least one animation**.
- [ ] Your pull request **does not modify any other files** in the repository.

#### Not normally needed
- [ ] Check this if you would like to discuss an improvement besides adding animations

**Note: if your pull request makes an improvement besides adding a CSS animation you will need to discuss this with the maintainers. You can help kickstart this process by explaining what your change does and why you are making it in the "What I did" section**

## What to expect

- If your pull request meets the checklist requirements it will be approved and merged by a maintainer
- If your pull request needs some changes. A maintainer will leave a comment requesting changes
- If your pull request significantly violates the criteria in the checklist it will be closed with feedback.

2024-10-20 09:18 UTC, LaurelineP requested changes
Aloha bis :)  @violin87 
Please address the following :
- [ ] Please address all the review I already gave you which are rementionned again on this review
- [ ] Please add a meta.json 
You can read the README.md if you don't know how to

2024-10-20 09:18 UTC, LaurelineP commented on Art/SumitDutta007-bubbles/styles.css
# Changes in a folder that does not belong to you
- [ ] Please remove any changes in `SumitDutta007-bubbles` folder

2024-10-20 09:18 UTC, LaurelineP commented on Art/violin87-activeSquares/index.html
## HTML review ( indentation + question ) 
- [ ] Please ensure a correct indentation for your HTML, nested divs are not correctly indented + it can make it hard to double check and it is a bad practice to correct


What is that comment about ? 
```<!-- I PURCHASED IMAGES -->```

2024-10-20 09:18 UTC, LaurelineP commented on Art/violin87-activeSquares/styles.css
> +
# Multiple empty lines to removes
As mentioned in your previous PRs
- [ ] Please remove the empty lines 
Here is a visual to help you where line 129 - line 146 are empty / so it is for line 152 to 156
![image](https://github.com/user-attachments/assets/e24df0d8-e909-47f3-98aa-a8559e0a5043)

2024-10-21 11:09 UTC, LaurelineP commented
Sets label to stale : no activity for >= 3 days

2024-10-23 14:30 UTC, violin87 commented
I apologize, I finally was able to figure out about meta.json. Thank you for your  patience. I am a new person)) Also, I didn't do any changes on other files. I particularly check this file. I don't know how did it happened

2024-10-24 12:01 UTC, LaurelineP requested changes
Thanks for your modifications @violin87 
You've maybe missed one feedback - removing empty lines in your css file.
Please address this.
After that this would be good to go

2024-10-24 12:01 UTC, LaurelineP commented on Art/violin87-activeSquares/styles.css
> +
[ 10/24/24 ] UP for the empty lines to remove

2024-10-27 04:36 UTC, violin87 commented
Did all changes with merging

2024-10-27 04:37 UTC, violin87 commented
I removed al extra line from CSS. Will you be able to let me merge? Thank you

2024-10-27 04:40 UTC, violin87 reviewed
Improved my CSS

2024-10-28 01:47 UTC, cadegore commented
@violin87 If you look under [**Files changed**](https://github.com/zero-to-mastery/Animation-Nation/pull/2791/files), it still show you modified other people's file

2024-10-28 19:28 UTC, violin87 commented
Hello, I really confused about that. I didn't touch any folders, I checked that foulder what was mentioned but I never changed anything there. Can it be just some bug? I don't know how to fix it since I can't change back something what I didn't change.  I would appreciate your help! Sorry for inconvenience

2024-10-29 09:12 UTC, LaurelineP commented on Art/violin87-activeSquares/styles.css
> +
Note: still has extra lines ... I will handle this

2024-10-29 09:13 UTC, merged

2024-10-29 18:44 UTC, violin87 commented
Thank you so much for your help!