add bouncing ball to the project
zero-to-mastery/Animation-Nation pull request #2792
Opened 2024-10-19 22:37 UTC by shrlaw

Please add my animation.

2024-10-20 09:23 UTC, LaurelineP requested changes
Aloha again @shrlaw 
Thanks for your new contribution,
Please address the given feedback so we could proceed in merging your PR :)

2024-10-20 09:23 UTC, LaurelineP commented on Art/shrlaw-bouncing/includes.js
## No JS allowed 
I noticed you've dubplicated the animation-nation includes.js - there is no need 
you can remove this file in your folder

2024-10-20 21:39 UTC, shrlaw commented
I made the requested change.

2024-10-22 07:04 UTC, shrlaw commented on Art/shrlaw-bouncing/includes.js
I removed includes.js.

2024-10-22 13:51 UTC, merged