Added Animations
zero-to-mastery/Animation-Nation pull request #2853
Opened 2024-10-28 20:07 UTC by mitul-bhatia

Thank you for making a pull request to ZTM's Animation Nation project. We will review your pull request as soon as we can, but keep in mind we can get very busy during Hacktoberfest.

While you're waiting, please look over this checklist. Feel free to write a description of what you did as well!

## What I did

i added my animation to it , it looks ashetic and is good to look

## Pull request checklist

- [ ] This pull request uses **HTML and CSS** only and provides a `meta.json` file.
- [ ] All files in this pull request are in a directory named: `<github_username>-<art_name>` without the <>.
- [ ] Your pull request contains `index.html` and `styles.css`.
	- [ ] Your html file is named exactly: `index.html`
	- [ ] Your css file is named exactly: `styles.css`
- [ ] Your pull request your `meta.json` with:
	- [ ] `githubHandle`: being your unique github user name,
	- [ ] `artName` : name of your animation
- [ ] Your submission includes **at least one animation**.
- [ ] Your pull request **does not modify any other files** in the repository.

#### Not normally needed
- [ ] Check this if you would like to discuss an improvement besides adding animations

**Note: if your pull request makes an improvement besides adding a CSS animation you will need to discuss this with the maintainers. You can help kickstart this process by explaining what your change does and why you are making it in the "What I did" section**

## What to expect

- If your pull request meets the checklist requirements it will be approved and merged by a maintainer
- If your pull request needs some changes. A maintainer will leave a comment requesting changes
- If your pull request significantly violates the criteria in the checklist it will be closed with feedback.

2024-10-28 20:07 UTC, mitul-bhatia commented
please accept it

2024-10-28 21:32 UTC, LaurelineP commented on Art/mitulBhatia-abs/icon.png
# Unnecessary picture
- [ ] Please remove the icon as this is generate when your PR is accepted automatically

2024-10-28 21:42 UTC, LaurelineP commented on Art/mitulBhatia-abs/index.html
# Unnecessary comments
- [ ] Please remove the comments

2024-10-28 21:53 UTC, LaurelineP requested changes
Aloha @mitul-bhatia 
Thanks for your contribution.
Please address the given feedback and the following
- [ ] the start of your foldername  should be the github handle ( you've added camelcase which does not match your github handle ) 
Please adjust

2024-10-31 04:50 UTC, mitul-bhatia commented
@LaurelineP i made all changes that were required now please accept it

2024-10-31 11:10 UTC, LaurelineP commented
> @LaurelineP i made all changes that were required now please accept it

There is still the file icon to be removed, please address this

2024-10-31 11:17 UTC, LaurelineP commented
For maintaining reasons, your PR is set to stale.
In the next 2 following days this will be closed if the given feedbacks and/or your PR is not correct.
@mitul-bhatia Please address the given feedbacks for your PR to be merged

2024-10-31 17:20 UTC, merged