fixed:New page html
zero-to-mastery/Animation-Nation pull request #2854
Opened 2024-10-29 01:07 UTC by User-Business

2024-10-29 03:08 UTC, cadegore requested changes
@User-Business Please update `style.css` to `styles.css`

2024-10-31 11:30 UTC, LaurelineP requested changes
Aloha @User-Business 
Thanks for your contribution
Please address the provided  feedbacks in order for us to validate your PR for a merge request

Also:
your code is indeed html and css but does not seem to do any animations.
The end challenge is to create an animation - most likely this should not be accepted as contribution.
This is why there is currently an invalid tag.
If this is the case, I'll check with maintainers, but this PR could be closed and this will be for the mentioned reasons.

Meanwhile, you could address the previous feedbacks :)

2024-10-31 11:30 UTC, LaurelineP commented on Art/User-Business-portfolio/index.html
> +  <link rel="stylesheet" href="style.css">
# Incorrect css file name
Currently the filename is matching the link's href
However this filename is incorrect according to both README requirements and the checklist.

- [ ] Please change your file name accordingly for both the css file name and this href

2024-10-31 11:30 UTC, LaurelineP commented on Art/User-Business-portfolio/style.css
# Incorrect css file name
Currently the filename is matching the link's href
However this filename is incorrect according to both README requirements and the checklist.

- [ ] Please change your file name accordingly for both the css file name and this href

2024-10-31 11:48 UTC, closed without merging