Bouncing ball-Animation
zero-to-mastery/Animation-Nation pull request #2863
Opened 2024-10-30 06:55 UTC by Anurag-singh-thakur

Thank you for making a pull request to ZTM's Animation Nation project. We will review your pull request as soon as we can, but keep in mind we can get very busy during Hacktoberfest.

While you're waiting, please look over this checklist. Feel free to write a description of what you did as well!

## What I did

*Optional: Edit this to tell us what you did!*

## Pull request checklist

- [ ] This pull request uses **HTML and CSS** only and provides a `meta.json` file.
- [x ] All files in this pull request are in a directory named: `<github_username>-<art_name>` without the <>.
- [ x] Your pull request contains `index.html` and `styles.css`.
	- [x ] Your html file is named exactly: `index.html`
	- [x ] Your css file is named exactly: `styles.css`
- [ ] Your pull request your `meta.json` with:
	- [ ] `githubHandle`: being your unique github user name,
	- [ ] `artName` : name of your animation
- [ x] Your submission includes **at least one animation**.
- [x ] Your pull request **does not modify any other files** in the repository.

#### Not normally needed
- [ ] Check this if you would like to discuss an improvement besides adding animations

**Note: if your pull request makes an improvement besides adding a CSS animation you will need to discuss this with the maintainers. You can help kickstart this process by explaining what your change does and why you are making it in the "What I did" section**

## What to expect

- If your pull request meets the checklist requirements it will be approved and merged by a maintainer
- If your pull request needs some changes. A maintainer will leave a comment requesting changes
- If your pull request significantly violates the criteria in the checklist it will be closed with feedback.

2024-10-30 13:26 UTC, LaurelineP commented on Art/Anurag-singh-thakur-Bouncing-Ball-Animation/index.html
# Incorrect link href source
- [ ] Once you've renamed your file as the PR checklist recommended, 
please adjust accordingly your href with the correct style name

2024-10-30 13:27 UTC, LaurelineP commented on Art/Anurag-singh-thakur-Rotating Sqaure/.vscode/settings.json
# Folder to delete `.vscode`
- [ ] Please remove your vscode configuration folder with its content

2024-10-30 13:30 UTC, LaurelineP requested changes
Aloha @Anurag-singh-thakur and thanks for your contributions.
Before we could merge your PR ;
- [ ] Please address the given feedbacks
- [ ] Please address the followings: 
  - Both contrubution folders are missing their own `meta.json` file
  Please refer to the README.md file for guidances

2024-10-30 13:34 UTC, LaurelineP commented on Art/Anurag-singh-thakur-Bouncing-Ball-Animation/styles.css
# Incorrect folder name
- [ ] Please adjust your folder name so it does not have any space character ( which is currently the case )

2024-10-30 13:39 UTC, LaurelineP commented on Art/Anurag-singh-thakur-Rotating Sqaure/index.html
# Incorrect filename
- [ ] Please remove any space characters in your folder name ( which currently has one ) 
- [ ] Also there is a typo you could fix: `Sqaure` --> `Square`

2024-10-30 14:00 UTC, Anurag-singh-thakur commented
It's done..please check and merge if there are any other errors then let me know .

2024-10-31 12:12 UTC, LaurelineP commented
> It's done..please check and merge if there are any other errors then let me know .

Aloha @Anurag-singh-thakur : I am not sure I understand what exactly has been done.
- there is stil the hidden .vscod configuration that needs to be removed
- there are still incorrect css files names for both contribution
- hence there are still issues with the HTNL link tag href for both of them

Morevover - the github did not detected any changes from your hand.

Please address the feedbacks .
If this PR is stalling without changes, or maybe because it start to be hard to understand what is asked or what to read in the PR: this will be closed and then, if you still want,  you could add contribution as recommended 1 folder at a time if this could facilitate things for you.

2024-11-03 11:09 UTC, LaurelineP commented
PR closed - feedback not addressed and stalling

2024-11-03 11:09 UTC, closed without merging